declare module 'lucide-react' {
  import type { FC, SVGProps } from 'react'

  interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number
    absoluteStrokeWidth?: boolean
  }

  export type Icon = FC<LucideProps>
  export type LucideIcon = Icon
  export const Activity: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUpDown: Icon
  export const Award: Icon
  export const BarChart2: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const BellRing: Icon
  export const BookMarked: Icon
  export const BookOpen: Icon
  export const Bookmark: Icon
  export const Bot: Icon
  export const Brain: Icon
  export const Briefcase: Icon
  export const Bug: Icon
  export const Building2: Icon
  export const Calendar: Icon
  export const CalendarClock: Icon
  export const CalendarDays: Icon
  export const Camera: Icon
  export const Check: Icon
  export const CheckCheck: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronUp: Icon
  export const ChevronsLeft: Icon
  export const ChevronsRight: Icon
  export const Circle: Icon
  export const ClipboardCheck: Icon
  export const ClipboardList: Icon
  export const Clock: Icon
  export const Code: Icon
  export const Columns: Icon
  export const Contact: Icon
  export const Copy: Icon
  export const CreditCard: Icon
  export const Crosshair: Icon
  export const Download: Icon
  export const Droplets: Icon
  export const Dumbbell: Icon
  export const Edit: Icon
  export const ExternalLink: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const File: Icon
  export const FileCheck: Icon
  export const FileSignature: Icon
  export const FileText: Icon
  export const FileWarning: Icon
  export const Film: Icon
  export const Filter: Icon
  export const Flame: Icon
  export const FolderOpen: Icon
  export const Gauge: Icon
  export const Gavel: Icon
  export const Globe: Icon
  export const GraduationCap: Icon
  export const Grid3X3: Icon
  export const GripVertical: Icon
  export const Hash: Icon
  export const Heart: Icon
  export const HelpCircle: Icon
  export const History: Icon
  export const Home: Icon
  export const Image: Icon
  export const ImageOff: Icon
  export const ImagePlus: Icon
  export const Info: Icon
  export const Kanban: Icon
  export const KeyRound: Icon
  export const Keyboard: Icon
  export const Landmark: Icon
  export const Layers: Icon
  export const LayoutDashboard: Icon
  export const Library: Icon
  export const Lightbulb: Icon
  export const List: Icon
  export const ListChecks: Icon
  export const Loader2: Icon
  export const Lock: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const Map: Icon
  export const MapPin: Icon
  export const Maximize2: Icon
  export const Megaphone: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const MessageSquareWarning: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Minus: Icon
  export const Monitor: Icon
  export const Moon: Icon
  export const MoreHorizontal: Icon
  export const Music2: Icon
  export const Network: Icon
  export const Package: Icon
  export const PenLine: Icon
  export const Pencil: Icon
  export const Phone: Icon
  export const Play: Icon
  export const Plus: Icon
  export const QrCode: Icon
  export const RefreshCw: Icon
  export const RotateCcw: Icon
  export const Save: Icon
  export const Scale: Icon
  export const ScrollText: Icon
  export const Search: Icon
  export const Send: Icon
  export const ZoomIn: Icon
  export const ServerCog: Icon
  export const Settings2: Icon
  export const Share2: Icon
  export const Shield: Icon
  export const ShieldAlert: Icon
  export const ShieldCheck: Icon
  export const Siren: Icon
  export const Smartphone: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Sun: Icon
  export const Tag: Icon
  export const Thermometer: Icon
  export const ThumbsUp: Icon
  export const Trash2: Icon
  export const TrendingDown: Icon
  export const TrendingUp: Icon
  export const Upload: Icon
  export const User: Icon
  export const UserCog: Icon
  export const UserPlus: Icon
  export const Users: Icon
  export const Video: Icon
  export const Volume2: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Wind: Icon
  export const Wrench: Icon
  export const X: Icon
  export const XCircle: Icon
  export const Zap: Icon
}
