-- ============================================================
-- Seed: barrios de CABA como localidades
-- provincia = 'Ciudad Autónoma de Buenos Aires'
-- ON CONFLICT DO NOTHING para idempotencia
-- ============================================================

INSERT INTO localidades (nombre, provincia) VALUES
('Agronomía',             'Ciudad Autónoma de Buenos Aires'),
('Almagro',               'Ciudad Autónoma de Buenos Aires'),
('Balvanera',             'Ciudad Autónoma de Buenos Aires'),
('Barracas',              'Ciudad Autónoma de Buenos Aires'),
('Belgrano',              'Ciudad Autónoma de Buenos Aires'),
('Boedo',                 'Ciudad Autónoma de Buenos Aires'),
('Caballito',             'Ciudad Autónoma de Buenos Aires'),
('Chacarita',             'Ciudad Autónoma de Buenos Aires'),
('Coghlan',               'Ciudad Autónoma de Buenos Aires'),
('Colegiales',            'Ciudad Autónoma de Buenos Aires'),
('Constitución',          'Ciudad Autónoma de Buenos Aires'),
('Flores',                'Ciudad Autónoma de Buenos Aires'),
('Floresta',              'Ciudad Autónoma de Buenos Aires'),
('La Boca',               'Ciudad Autónoma de Buenos Aires'),
('La Paternal',           'Ciudad Autónoma de Buenos Aires'),
('Liniers',               'Ciudad Autónoma de Buenos Aires'),
('Mataderos',             'Ciudad Autónoma de Buenos Aires'),
('Microcentro',           'Ciudad Autónoma de Buenos Aires'),
('Monte Castro',          'Ciudad Autónoma de Buenos Aires'),
('Montserrat',            'Ciudad Autónoma de Buenos Aires'),
('Nueva Pompeya',         'Ciudad Autónoma de Buenos Aires'),
('Núñez',                 'Ciudad Autónoma de Buenos Aires'),
('Palermo',               'Ciudad Autónoma de Buenos Aires'),
('Parque Avellaneda',     'Ciudad Autónoma de Buenos Aires'),
('Parque Chacabuco',      'Ciudad Autónoma de Buenos Aires'),
('Parque Chas',           'Ciudad Autónoma de Buenos Aires'),
('Parque Patricios',      'Ciudad Autónoma de Buenos Aires'),
('Puerto Madero',         'Ciudad Autónoma de Buenos Aires'),
('Recoleta',              'Ciudad Autónoma de Buenos Aires'),
('Retiro',                'Ciudad Autónoma de Buenos Aires'),
('Saavedra',              'Ciudad Autónoma de Buenos Aires'),
('San Cristóbal',         'Ciudad Autónoma de Buenos Aires'),
('San Nicolás',           'Ciudad Autónoma de Buenos Aires'),
('San Telmo',             'Ciudad Autónoma de Buenos Aires'),
('Versalles',             'Ciudad Autónoma de Buenos Aires'),
('Villa Crespo',          'Ciudad Autónoma de Buenos Aires'),
('Villa del Parque',      'Ciudad Autónoma de Buenos Aires'),
('Villa Devoto',          'Ciudad Autónoma de Buenos Aires'),
('Villa General Mitre',   'Ciudad Autónoma de Buenos Aires'),
('Villa Lugano',          'Ciudad Autónoma de Buenos Aires'),
('Villa Luro',            'Ciudad Autónoma de Buenos Aires'),
('Villa Ortúzar',         'Ciudad Autónoma de Buenos Aires'),
('Villa Pueyrredón',      'Ciudad Autónoma de Buenos Aires'),
('Villa Real',            'Ciudad Autónoma de Buenos Aires'),
('Villa Riachuelo',       'Ciudad Autónoma de Buenos Aires'),
('Villa Santa Rita',      'Ciudad Autónoma de Buenos Aires'),
('Villa Soldati',         'Ciudad Autónoma de Buenos Aires'),
('Villa Urquiza',         'Ciudad Autónoma de Buenos Aires')
ON CONFLICT (nombre, provincia) DO NOTHING;
