-- =====================================================================
-- Seed OFICIAL Anexo IV (Dec. 351/79) — Tablas 1 y 2 de Iluminación
-- Data de referencia provista por el cliente (oficial).
-- Tablas destino (ya creadas): dec351_iluminacion_tabla1 / _tabla2
-- =====================================================================

-- 1) Limpiar ejemplos sembrados por la migración fundacional
DELETE FROM dec351_iluminacion_tabla1;
DELETE FROM dec351_iluminacion_tabla2;

-- ---------------------------------------------------------------------
-- TABLA 1 — Intensidad media de iluminación según clase de tarea visual
-- ---------------------------------------------------------------------
INSERT INTO dec351_iluminacion_tabla1 (clase_tarea, detalle, lux_min, lux_max, orden) VALUES
('Visión ocasional solamente', 'Movimientos seguros en lugares de poco tránsito: sala de calderas, depósito de materiales voluminosos.', 100, 100, 1),
('Tareas intermitentes ordinarias y fáciles, con contrastes fuertes', 'Trabajos simples intermitentes y mecánicos; inspección general; contado de partes de stock; colocación de maquinaria pesada.', 100, 300, 2),
('Tarea moderadamente crítica y prolongada, con detalles medianos', 'Trabajos medianos mecánicos y manuales, inspección y montaje; trabajos comunes de oficina: lectura, escritura, archivo.', 300, 750, 3),
('Tareas severas y prolongadas, de poco contraste', 'Trabajos finos mecánicos y manuales, montajes e inspección; pintura extrafina, sopleteado, costura de ropa oscura.', 750, 1500, 4),
('Tareas muy severas y prolongadas, con detalles minuciosos o muy poco contraste', 'Montaje e inspección de mecanismos delicados; fabricación de herramientas y matrices; inspección con calibrador; molienda fina.', 1500, 3000, 5),
('Trabajo fino de relojería y reparación', 'Trabajo fino de relojería y reparación.', 3000, 3000, 6),
('Tareas excepcionales, difíciles o importantes', 'Casos especiales, p.ej. iluminación del campo operatorio en sala de cirugía.', 5000, 10000, 7);

-- ---------------------------------------------------------------------
-- TABLA 2 — Intensidad media de iluminación por rubro / local / tarea
-- (aplanado fiel del listado oficial)
-- ---------------------------------------------------------------------
INSERT INTO dec351_iluminacion_tabla2 (rubro, local, tarea, lux_min, orden) VALUES
-- Vivienda
('Vivienda', 'Baño', 'Iluminación general', 100, 1),
('Vivienda', 'Baño', 'Iluminación localizada sobre espejos (sobre plano vertical)', 200, 2),
('Vivienda', 'Dormitorio', 'Iluminación general', 200, 3),
('Vivienda', 'Dormitorio', 'Iluminación localizada (cama, espejo)', 200, 4),
('Vivienda', 'Cocina', 'Iluminación sobre zona de trabajo (cocina, pileta, mesada)', 200, 5),
-- Centros Comerciales de Mediana Importancia
('Centros Comerciales de Mediana Importancia', 'Centros Comerciales de Mediana Importancia', 'Iluminación general', 1000, 6),
('Centros Comerciales de Mediana Importancia', 'Centros Comerciales de Mediana Importancia', 'Depósito de mercaderías', 300, 7),
('Centros Comerciales de Mediana Importancia', 'Centros Comerciales de Mediana Importancia', 'Iluminación general', 500, 8),
-- Hoteles
('Hoteles', 'Circulaciones', 'Pasillos, palier y ascensor', 100, 9),
('Hoteles', 'Circulaciones', 'Hall de entrada', 300, 10),
('Hoteles', 'Circulaciones', 'Escalera', 100, 11),
('Hoteles', 'Local para ropa blanca', 'Iluminación general', 200, 12),
('Hoteles', 'Local para ropa blanca', 'Costura', 400, 13),
('Hoteles', 'Local para ropa blanca', 'Lavandería', 100, 14),
('Hoteles', 'Hoteles', 'Vestuarios', 100, 15),
('Hoteles', 'Hoteles', 'Sótano/bodegas', 70, 16),
('Hoteles', 'Hoteles', 'Depósitos', 100, 17),
-- Garajes y Estaciones de Servicio
('Garajes y Estaciones de Servicio', 'Garajes y Estaciones de Servicio', 'Iluminación general', 100, 18),
('Garajes y Estaciones de Servicio', 'Garajes y Estaciones de Servicio', 'Gomería', 200, 19),
-- Oficinas
('Oficinas', 'Oficinas', 'Halls para el público', 200, 20),
('Oficinas', 'Oficinas', 'Contaduría/tabulaciones/teneduría de libros/operaciones bursátiles/lectura de reproducciones/bosquejos rápidos', 500, 21),
('Oficinas', 'Oficinas', 'Trabajo general de oficinas/lectura de buenas reproducciones/transcripción a mano/archivo/índices/distribución de correspondencia', 500, 22),
('Oficinas', 'Oficinas', 'Trabajos especiales de oficina (sistema de computación de datos)', 750, 23),
('Oficinas', 'Oficinas', 'Sala de conferencias', 300, 24),
('Oficinas', 'Oficinas', 'Circulación', 200, 25),
-- Bancos
('Bancos', 'Bancos', 'Iluminación general', 500, 26),
('Bancos', 'Bancos', 'Sobre zonas de escritura y cajas', 750, 27),
('Bancos', 'Bancos', 'Sala de caudales', 500, 28),
-- Industrias Alimenticias
('Industrias Alimenticias', 'Mataderos municipales', 'Recepción', 50, 29),
('Industrias Alimenticias', 'Mataderos municipales', 'Corrales: Inspección', 300, 30),
('Industrias Alimenticias', 'Mataderos municipales', 'Corrales: Permanencia', 50, 31),
('Industrias Alimenticias', 'Mataderos municipales', 'Matanza', 100, 32),
('Industrias Alimenticias', 'Mataderos municipales', 'Deshollado', 100, 33),
('Industrias Alimenticias', 'Mataderos municipales', 'Escaldado', 100, 34),
('Industrias Alimenticias', 'Mataderos municipales', 'Evisceración', 300, 35),
('Industrias Alimenticias', 'Mataderos municipales', 'Inspección', 300, 36),
('Industrias Alimenticias', 'Mataderos municipales', 'Mostradores de venta', 300, 37),
('Industrias Alimenticias', 'Frigoríficos', 'Cámaras frías', 50, 38),
('Industrias Alimenticias', 'Frigoríficos', 'Salas de máquinas', 150, 39),
('Industrias Alimenticias', 'Conservas de carne', 'Corte/deshuesado/elección', 300, 40),
('Industrias Alimenticias', 'Conservas de carne', 'Cocción', 100, 41),
('Industrias Alimenticias', 'Conservas de carne', 'Preparación de patés/envasado', 150, 42),
('Industrias Alimenticias', 'Conservas de carne', 'Esterilización', 150, 43),
('Industrias Alimenticias', 'Conservas de carne', 'Inspección', 300, 44),
('Industrias Alimenticias', 'Conservas de carne', 'Preparación de embutidos', 300, 45),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Recepción', 300, 46),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Lavado y preparación', 100, 47),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Cocción', 100, 48),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Envasado', 300, 49),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Esterilización', 100, 50),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Inspección', 300, 51),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Embalaje', 200, 52),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Preparación de pescado ahumado', 300, 53),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Secado', 300, 54),
('Industrias Alimenticias', 'Conservas de pescado y mariscos', 'Cámara de secado', 50, 55),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Recepción y selección', 300, 56),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Preparación mecanizada', 150, 57),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Envasado', 150, 58),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Esterilización', 150, 59),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Cámara de procesado', 50, 60),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Inspección', 300, 61),
('Industrias Alimenticias', 'Conservas de verduras y frutas', 'Embalaje', 200, 62),
('Industrias Alimenticias', 'Molinos harineros', 'Depósito de granos', 100, 63),
('Industrias Alimenticias', 'Molinos harineros', 'Limpieza', 150, 64),
('Industrias Alimenticias', 'Molinos harineros', 'Molienda y tamizado', 100, 65),
('Industrias Alimenticias', 'Molinos harineros', 'Clasificación de harinas', 100, 66),
('Industrias Alimenticias', 'Molinos harineros', 'Colocación de bolsas', 300, 67),
('Industrias Alimenticias', 'Silos', 'Zona de recepción', 100, 68),
('Industrias Alimenticias', 'Silos', 'Circulaciones', 100, 69),
('Industrias Alimenticias', 'Silos', 'Sala de comando', 300, 70),
('Industrias Alimenticias', 'Panaderías', 'Depósito de harinas', 100, 71),
('Industrias Alimenticias', 'Panaderías', 'Amasado sobre artesas', 200, 72),
('Industrias Alimenticias', 'Panaderías', 'Cocción iluminación general', 200, 73),
('Industrias Alimenticias', 'Panaderías', 'Delante de los hornos', 300, 74),
('Industrias Alimenticias', 'Fábrica de bizcochos', 'Depósito de harinas', 100, 75),
('Industrias Alimenticias', 'Fábrica de bizcochos', 'Local de elaboración', 200, 76),
('Industrias Alimenticias', 'Fábrica de bizcochos', 'Inspección', 300, 77),
('Industrias Alimenticias', 'Fábrica de bizcochos', 'Depósito del producto elaborado', 100, 78),
('Industrias Alimenticias', 'Pastas alimenticias', 'Depósito de harinas', 100, 79),
('Industrias Alimenticias', 'Pastas alimenticias', 'Local de elaboración', 200, 80),
('Industrias Alimenticias', 'Pastas alimenticias', 'Secado', 50, 81),
('Industrias Alimenticias', 'Pastas alimenticias', 'Inspección y empaquetado', 300, 82),
('Industrias Alimenticias', 'Torrefacción de café', 'Depósito', 100, 83),
('Industrias Alimenticias', 'Torrefacción de café', 'Torrefacción', 200, 84),
('Industrias Alimenticias', 'Torrefacción de café', 'Inspección y empaquetado', 300, 85),
('Industrias Alimenticias', 'Fábrica de chocolate', 'Depósito', 100, 86),
('Industrias Alimenticias', 'Fábrica de chocolate', 'Preparación de chocolate', 200, 87),
('Industrias Alimenticias', 'Fábrica de chocolate', 'Preparación de cacao en polvo', 200, 88),
('Industrias Alimenticias', 'Fábrica de chocolate', 'Inspección y empaquetado', 300, 89),
('Industrias Alimenticias', 'Usinas pasteurizadoras', 'Recepción y control de materia prima', 200, 90),
('Industrias Alimenticias', 'Usinas pasteurizadoras', 'Pasteurización', 300, 91),
('Industrias Alimenticias', 'Usinas pasteurizadoras', 'Envasado', 300, 92),
('Industrias Alimenticias', 'Usinas pasteurizadoras', 'Encajonado', 200, 93),
('Industrias Alimenticias', 'Usinas pasteurizadoras', 'Laboratorio', 600, 94),
('Industrias Alimenticias', 'Fábrica de derivados lácteos', 'Elaboración', 300, 95),
('Industrias Alimenticias', 'Fábrica de derivados lácteos', 'Cámaras frías', 50, 96),
('Industrias Alimenticias', 'Fábrica de derivados lácteos', 'Sala de máquinas', 150, 97),
('Industrias Alimenticias', 'Fábrica de derivados lácteos', 'Depósitos de quesos', 100, 98),
('Industrias Alimenticias', 'Fábrica de derivados lácteos', 'Envasado', 300, 99),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Recepción de materia prima', 100, 100),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Local de elaboración', 200, 101),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Local de cubas circulaciones', 200, 102),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Curado y embotellado', 300, 103),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Embotellado iluminación general', 150, 104),
('Industrias Alimenticias', 'Vinos y bebidas alcohólicas', 'Embalaje', 150, 105),
('Industrias Alimenticias', 'Cervezas y malterías', 'Depósito', 100, 106),
('Industrias Alimenticias', 'Cervezas y malterías', 'Preparación de la malta', 100, 107),
('Industrias Alimenticias', 'Cervezas y malterías', 'Trituración y colocación de la malta en bolsas', 200, 108),
('Industrias Alimenticias', 'Cervezas y malterías', 'Elaboración', 300, 109),
('Industrias Alimenticias', 'Cervezas y malterías', 'Locales de fermentación', 100, 110),
('Industrias Alimenticias', 'Cervezas y malterías', 'Embotellado lavado y llenado', 150, 111),
('Industrias Alimenticias', 'Cervezas y malterías', 'Embalaje', 150, 112),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Recepción de materia prima', 100, 113),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Elaboración del azúcar iluminación general', 200, 114),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Turbinas de trituración', 300, 115),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Almacenamiento de azúcar', 100, 116),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Embolsado', 200, 117),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Manómetros/niveles iluminación localizada', 300, 118),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Sala de máquinas', 150, 119),
('Industrias Alimenticias', 'Fábrica de azúcar', 'Tableros de distribución y laboratorios', 300, 120),
('Industrias Alimenticias', 'Refinerías', 'Iluminación general', 100, 121),
('Industrias Alimenticias', 'Refinerías', 'Amasado sobre cada turbina', 300, 122),
('Industrias Alimenticias', 'Refinerías', 'Molienda sobre la máquina', 300, 123),
('Industrias Alimenticias', 'Refinerías', 'Empaque', 200, 124),
('Industrias Alimenticias', 'Fábricas de productos de confitería', 'Cocción y preparación de pastas iluminación general', 200, 125),
('Industrias Alimenticias', 'Fábricas de productos de confitería', 'Cocción y preparación de pastas iluminación localizada', 400, 126),
('Industrias Alimenticias', 'Fábricas de productos de confitería', 'Elaboración y terminación iluminación general', 200, 127),
('Industrias Alimenticias', 'Fábricas de productos de confitería', 'Elaboración y terminación iluminación localizada', 400, 128),
('Industrias Alimenticias', 'Fábricas de productos de confitería', 'Depósitos', 100, 129),
-- Metalúrgica
('Metalúrgica', 'Fundiciones', 'Depósito de barras y lingotes', 100, 130),
('Metalúrgica', 'Fundiciones', 'Arena (transporte/tamizado/mezcla, transportadoras/elevadores/trituradores/tamices)', 100, 131),
('Metalúrgica', 'Fundiciones', 'Fabricación de noyos fino', 300, 132),
('Metalúrgica', 'Fundiciones', 'Fabricación de noyos grueso', 200, 133),
('Metalúrgica', 'Fundiciones', 'Depósito de placas modelos', 100, 134),
('Metalúrgica', 'Fundiciones', 'Zona de pesado de cargas', 100, 135),
('Metalúrgica', 'Taller de moldeo', 'Iluminación general', 250, 136),
('Metalúrgica', 'Taller de moldeo', 'Iluminación localizada en moldes', 500, 137),
('Metalúrgica', 'Taller de moldeo', 'Llenado de moldes', 200, 138),
('Metalúrgica', 'Taller de moldeo', 'Desmolde', 100, 139),
('Metalúrgica', 'Acerías', 'Depósito de minerales y carbón', 100, 140),
('Metalúrgica', 'Acerías', 'Zona de colado', 100, 141),
('Metalúrgica', 'Acerías', 'Trenes de laminación', 200, 142),
('Metalúrgica', 'Fragüe / Fabricación de alambre', 'Laminación en frío', 300, 143),
('Metalúrgica', 'Fragüe / Fabricación de alambre', 'Laminación en caliente', 200, 144),
('Metalúrgica', 'Fragüe / Fabricación de alambre', 'Depósito de productos terminados', 100, 145),
('Metalúrgica', 'Mecánica general', 'Depósito de materiales', 100, 146),
('Metalúrgica', 'Inspección y control de calidad', 'Trabajo grueso (contar/control grueso)', 300, 147),
('Metalúrgica', 'Inspección y control de calidad', 'Trabajo mediano (ensamble previo)', 600, 148),
('Metalúrgica', 'Inspección y control de calidad', 'Trabajo fino (dispositivos de calibración, mecánica de precisión, instrumentos)', 1200, 149),
('Metalúrgica', 'Inspección y control de calidad', 'Trabajo muy fino (calibración e inspección de piezas pequeñas)', 2000, 150),
('Metalúrgica', 'Inspección y control de calidad', 'Trabajo minucioso (instrumentos muy pequeños)', 3000, 151),
('Metalúrgica', 'Talleres de montaje', 'Trabajo grueso (máquinas pesadas)', 200, 152),
('Metalúrgica', 'Talleres de montaje', 'Trabajo mediano (máquinas, chasis de vehículos)', 400, 153),
('Metalúrgica', 'Talleres de montaje', 'Trabajo fino (localizada)', 1200, 154),
('Metalúrgica', 'Talleres de montaje', 'Trabajo muy fino (instrumentos/mecanismos pequeños, localizada)', 2000, 155),
('Metalúrgica', 'Talleres de montaje', 'Trabajo minucioso (localizada)', 3000, 156),
('Metalúrgica', 'Depósito de piezas sueltas y productos terminados', 'Iluminación general', 100, 157),
('Metalúrgica', 'Depósito de piezas sueltas y productos terminados', 'Áreas específicas (mesas, ventanillas)', 300, 158),
('Metalúrgica', 'Metalúrgica', 'Elaboración de metales en láminas (banco y máquinas especiales)', 500, 159),
('Metalúrgica', 'Máquinas/herramientas/bancos de trabajo', 'Iluminación general', 300, 160),
('Metalúrgica', 'Máquinas/herramientas/bancos de trabajo', 'Iluminación localizada para trabajos delicados/verificación de medidas/rectificación de precisión', 1000, 161),
('Metalúrgica', 'Máquinas/herramientas/bancos de trabajo', 'Trabajo de piezas pequeñas/rectificación medianas/fabricación de herramientas/ajuste de máquinas', 500, 162),
('Metalúrgica', 'Máquinas/herramientas/bancos de trabajo', 'Soldadura', 300, 163),
('Metalúrgica', 'Máquinas/herramientas/bancos de trabajo', 'Tratamiento superficial de metales', 300, 164),
('Metalúrgica', 'Pintura', 'Preparación de los elementos', 400, 165),
('Metalúrgica', 'Pintura', 'Preparación/dosaje/mezcla de colores', 1000, 166),
('Metalúrgica', 'Pintura', 'Cabina de pulverización', 400, 167),
('Metalúrgica', 'Pintura', 'Pulido y terminación', 600, 168),
('Metalúrgica', 'Pintura', 'Inspección y retoque', 600, 169),
-- Del Calzado
('Del Calzado', 'Del Calzado', 'Clasificación/marcado/corte', 400, 170),
('Del Calzado', 'Del Calzado', 'Costura', 600, 171),
('Del Calzado', 'Del Calzado', 'Inspección', 1000, 172),
-- Centrales Eléctricas
('Centrales Eléctricas', 'Centrales Eléctricas', 'Estaciones de transformación exteriores circulación', 100, 173),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Locales de máquinas rotativas', 200, 174),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Locales de equipos auxiliares (máquinas estáticas/interruptores)', 200, 175),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Tableros de aparatos de control y medición iluminación general', 200, 176),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Tableros de aparatos de control y medición sobre el plano de lectura', 400, 177),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Subestaciones transformadoras exteriores', 10, 178),
('Centrales Eléctricas', 'Centrales Eléctricas', 'Subestaciones transformadoras interiores', 100, 179),
-- Cerámica
('Cerámica', 'Cerámica', 'Preparación de arcillas/amasado/molde/prensas/hornos/secadores', 200, 180),
('Cerámica', 'Cerámica', 'Barnizado y decoración trabajos finos', 800, 181),
('Cerámica', 'Cerámica', 'Barnizado y decoración trabajos medianos', 400, 182),
('Cerámica', 'Cerámica', 'Inspección localizada', 1000, 183),
-- Del Cuero
('Del Cuero', 'Del Cuero', 'Limpieza/curtido/igualado/sobado/barnizado/secadores/terminación', 200, 184),
('Del Cuero', 'Del Cuero', 'Inspección y trabajos especiales', 600, 185),
-- Imprenta
('Imprenta', 'Imprenta', 'Taller de tipografía iluminación general/compaginación/prensa para pruebas', 300, 186),
('Imprenta', 'Imprenta', 'Mesa de correctores/pupitres p/composición', 800, 187),
('Imprenta', 'Imprenta', 'Taller de linotipos iluminación general', 300, 188),
('Imprenta', 'Imprenta', 'Taller de linotipos sobre máquinas en salida de letras y teclado', 400, 189),
('Imprenta', 'Imprenta', 'Inspección de impresión de colores', 1000, 190),
('Imprenta', 'Imprenta', 'Rotativas tinteros y cilindros', 300, 191),
('Imprenta', 'Imprenta', 'Recepción', 400, 192),
('Imprenta', 'Imprenta', 'Grabado a mano localizada', 1000, 193),
('Imprenta', 'Imprenta', 'Litografía', 700, 194),
-- Joyería y Relojería
('Joyería y Relojería', 'Joyería y Relojería', 'Zona de trabajo iluminación general', 400, 195),
('Joyería y Relojería', 'Joyería y Relojería', 'Trabajos finos', 900, 196),
('Joyería y Relojería', 'Joyería y Relojería', 'Trabajos minuciosos', 2000, 197),
('Joyería y Relojería', 'Joyería y Relojería', 'Corte de gemas/pulido/engarce', 1300, 198),
-- Maderera
('Maderera', 'Aserraderos', 'Iluminación general', 100, 199),
('Maderera', 'Aserraderos', 'Zona de corte y clasificación', 200, 200),
('Maderera', 'Carpintería', 'Iluminación general', 100, 201),
('Maderera', 'Carpintería', 'Zona de bancos y máquinas', 300, 202),
('Maderera', 'Carpintería', 'Trabajos de terminación de inspección', 600, 203),
('Maderera', 'Manufactura de muebles', 'Selección del enchapado y preparación', 900, 204),
('Maderera', 'Manufactura de muebles', 'Armado y terminación', 400, 205),
('Maderera', 'Manufactura de muebles', 'Marquetería', 600, 206),
('Maderera', 'Manufactura de muebles', 'Inspección', 600, 207),
-- Papelera
('Papelera', 'Papelera', 'Local de máquinas', 100, 208),
('Papelera', 'Papelera', 'Corte/terminación', 300, 209),
('Papelera', 'Papelera', 'Inspección', 500, 210),
('Papelera', 'Manufacturas de cajas', 'Encartonado fijo', 300, 211),
('Papelera', 'Manufacturas de cajas', 'Cartones ordinarios/cajones', 200, 212),
-- Química
('Química', 'Planta de procesamiento', 'Circulación general', 100, 213),
('Química', 'Planta de procesamiento', 'Iluminación general sobre escaleras y pasarelas', 200, 214),
('Química', 'Planta de procesamiento', 'Sobre aparatos (plano vertical)', 200, 215),
('Química', 'Planta de procesamiento', 'Sobre mesas y pupitres', 400, 216),
('Química', 'Laboratorio de ensayo y control', 'Iluminación general', 400, 217),
('Química', 'Laboratorio de ensayo y control', 'Sobre plano de lectura de aparatos', 600, 218),
('Química', 'Caucho', 'Preparación de la materia prima', 200, 219),
('Química', 'Caucho', 'Fabricación de neumáticos', 200, 220),
('Química', 'Caucho', 'Vulcanización de envolturas y cámaras de aire', 300, 221),
('Química', 'Jabones', 'Iluminación general', 300, 222),
('Química', 'Jabones', 'Panel de control', 400, 223),
('Química', 'Pinturas', 'Procesos automáticos', 200, 224),
('Química', 'Pinturas', 'Mezcla de pinturas', 600, 225),
('Química', 'Pinturas', 'Combinación de colores', 1000, 226),
('Química', 'Plásticos', 'Calandrado/extrusión/inyección/compresión/moldeado por soplado', 300, 227),
('Química', 'Plásticos', 'Fabricación de láminas/conformado/maquinado/fresado/pulido/cementado/recortado', 400, 228),
('Química', 'Depósito/almacenes/salas de empaque', 'Piezas grandes', 100, 229),
('Química', 'Depósito/almacenes/salas de empaque', 'Piezas pequeñas', 200, 230),
('Química', 'Depósito/almacenes/salas de empaque', 'Expedición de mercaderías', 300, 231),
-- Del Tabaco
('Del Tabaco', 'Del Tabaco', 'Proceso completo', 400, 232),
-- Textil
('Textil', 'Tejidos de algodón y lino', 'Mezcla/cardado/estirado', 200, 233),
('Textil', 'Tejidos de algodón y lino', 'Torcido/peinado/hilado/husos', 200, 234),
('Textil', 'Tejidos de algodón y lino', 'Urdimbre sobre los peines', 700, 235),
('Textil', 'Tejidos de algodón y lino', 'Tejido telas claras y medianas', 400, 236),
('Textil', 'Tejidos de algodón y lino', 'Tejido telas oscuras', 700, 237),
('Textil', 'Tejidos de algodón y lino', 'Inspección telas claras y medianas', 600, 238),
('Textil', 'Tejidos de algodón y lino', 'Inspección telas oscuras', 900, 239),
('Textil', 'Lana', 'Cardado/lavado/peinado/retorcido/tintura', 200, 240),
('Textil', 'Lana', 'Lavada/urdimbre', 200, 241),
('Textil', 'Lana', 'Tejidos telas claras y medianas', 600, 242),
('Textil', 'Lana', 'Tejidos telas oscuras', 900, 243),
('Textil', 'Lana', 'Máquinas de tejidos de punto', 900, 244),
('Textil', 'Lana', 'Inspección telas claras y medianas', 1200, 245),
('Textil', 'Lana', 'Inspección telas oscuras', 1500, 246),
('Textil', 'Seda natural y sintética', 'Embebido/teñido/texturado', 300, 247),
('Textil', 'Seda natural y sintética', 'Urdimbre', 700, 248),
('Textil', 'Seda natural y sintética', 'Hilado', 450, 249),
('Textil', 'Seda natural y sintética', 'Tejidos telas claras y medianas', 600, 250),
('Textil', 'Seda natural y sintética', 'Tejidos telas oscuras', 900, 251),
('Textil', 'Yute', 'Hilado/tejido con lanzaderas/devanado', 200, 252),
('Textil', 'Yute', 'Calandrado', 200, 253),
-- Del Vestido
('Del Vestido', 'Sombreros', 'Limpieza/tintura/terminación/forma/alisado/planchado', 400, 254),
('Del Vestido', 'Sombreros', 'Costura', 600, 255),
('Del Vestido', 'Vestimenta', 'Sobre máquinas', 600, 256),
('Del Vestido', 'Vestimenta', 'Manual', 800, 257),
('Del Vestido', 'Fábrica de guantes', 'Prensa/tejidos/muestreo/corte', 400, 258),
('Del Vestido', 'Fábrica de guantes', 'Costura', 600, 259),
('Del Vestido', 'Fábrica de guantes', 'Control', 1000, 260),
-- Del Vidrio
('Del Vidrio', 'Del Vidrio', 'Sala de mezclado iluminación general', 200, 261),
('Del Vidrio', 'Del Vidrio', 'Zona de dosificación', 400, 262),
('Del Vidrio', 'Del Vidrio', 'Local de horno', 100, 263),
('Del Vidrio', 'Del Vidrio', 'Local de manufactura mecánica sobre máquinas iluminación general', 200, 264),
('Del Vidrio', 'Del Vidrio', 'Local de manufactura manual iluminación general', 200, 265),
('Del Vidrio', 'Del Vidrio', 'Corte/pulido/biselado', 400, 266),
('Del Vidrio', 'Del Vidrio', 'Terminación general', 200, 267),
('Del Vidrio', 'Del Vidrio', 'Inspección general', 400, 268);
