-- ============================================================
-- Normalización localidad/provincia → tabla localidades + FK
-- ============================================================

-- Tabla de referencia
CREATE TABLE localidades (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre     text        NOT NULL,
  provincia  text        NOT NULL,
  is_active  boolean     NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_localidad_provincia UNIQUE (nombre, provincia)
);

CREATE INDEX idx_localidades_provincia ON localidades(provincia);

ALTER TABLE localidades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "localidades_select_auth" ON localidades FOR SELECT TO authenticated USING (true);
CREATE POLICY "localidades_write_dev"   ON localidades FOR ALL   TO authenticated
  USING  ((SELECT system_role FROM profiles WHERE id = auth.uid()) = 'developer')
  WITH CHECK ((SELECT system_role FROM profiles WHERE id = auth.uid()) = 'developer');

-- ── Seed ─────────────────────────────────────────────────────

INSERT INTO localidades (nombre, provincia) VALUES

-- Ciudad Autónoma de Buenos Aires
('Ciudad Autónoma de Buenos Aires', 'Ciudad Autónoma de Buenos Aires'),

-- Buenos Aires — GBA Zona Norte
('San Isidro',                    'Buenos Aires'),
('Martínez',                      'Buenos Aires'),
('Beccar',                        'Buenos Aires'),
('Acassuso',                      'Buenos Aires'),
('La Lucila',                     'Buenos Aires'),
('Olivos',                        'Buenos Aires'),
('Villa Martelli',                'Buenos Aires'),
('Florida',                       'Buenos Aires'),
('Munro',                         'Buenos Aires'),
('Vicente López',                 'Buenos Aires'),
('Tigre',                         'Buenos Aires'),
('Don Torcuato',                  'Buenos Aires'),
('El Talar',                      'Buenos Aires'),
('General Pacheco',               'Buenos Aires'),
('Rincón de Milberg',             'Buenos Aires'),
('Ricardo Rojas',                 'Buenos Aires'),
('San Fernando',                  'Buenos Aires'),
('General San Martín',            'Buenos Aires'),
('Villa Ballester',               'Buenos Aires'),
('Villa Lynch',                   'Buenos Aires'),
('San Andrés',                    'Buenos Aires'),
('Tres de Febrero',               'Buenos Aires'),
('Caseros',                       'Buenos Aires'),
('El Palomar',                    'Buenos Aires'),
('Ciudadela',                     'Buenos Aires'),
('Hurlingham',                    'Buenos Aires'),
('William Morris',                'Buenos Aires'),
('Ituzaingó',                     'Buenos Aires'),
('Morón',                         'Buenos Aires'),
('Haedo',                         'Buenos Aires'),
('Castelar',                      'Buenos Aires'),
('Malvinas Argentinas',           'Buenos Aires'),
('Los Polvorines',                'Buenos Aires'),
('Grand Bourg',                   'Buenos Aires'),
('Tortuguitas',                   'Buenos Aires'),
('Pablo Nogués',                  'Buenos Aires'),
('Pilar',                         'Buenos Aires'),
('Del Viso',                      'Buenos Aires'),
('Manuel Alberti',                'Buenos Aires'),
('Presidente Derqui',             'Buenos Aires'),
('Escobar',                       'Buenos Aires'),
('Garín',                         'Buenos Aires'),
('Belén de Escobar',              'Buenos Aires'),
('Campana',                       'Buenos Aires'),
('Zárate',                        'Buenos Aires'),
('Lima',                          'Buenos Aires'),
('Luján',                         'Buenos Aires'),
('General Rodríguez',             'Buenos Aires'),
('Marcos Paz',                    'Buenos Aires'),
('José C. Paz',                   'Buenos Aires'),

-- Buenos Aires — GBA Zona Oeste
('San Justo',                     'Buenos Aires'),
('Ramos Mejía',                   'Buenos Aires'),
('González Catán',                'Buenos Aires'),
('Gregorio de Laferrère',         'Buenos Aires'),
('Isidro Casanova',               'Buenos Aires'),
('Rafael Castillo',               'Buenos Aires'),
('Tapiales',                      'Buenos Aires'),
('La Tablada',                    'Buenos Aires'),
('Lomas del Mirador',             'Buenos Aires'),
('Villa Luzuriaga',               'Buenos Aires'),
('Ciudad Evita',                  'Buenos Aires'),
('Virrey del Pino',               'Buenos Aires'),
('La Matanza',                    'Buenos Aires'),
('Merlo',                         'Buenos Aires'),
('San Antonio de Padua',          'Buenos Aires'),
('Pontevedra',                    'Buenos Aires'),
('Moreno',                        'Buenos Aires'),
('Francisco Álvarez',             'Buenos Aires'),
('General Las Heras',             'Buenos Aires'),

-- Buenos Aires — GBA Zona Sur
('Lomas de Zamora',               'Buenos Aires'),
('Banfield',                      'Buenos Aires'),
('Temperley',                     'Buenos Aires'),
('Turdera',                       'Buenos Aires'),
('Lanús',                         'Buenos Aires'),
('Remedios de Escalada',          'Buenos Aires'),
('Monte Chingolo',                'Buenos Aires'),
('Lanús Este',                    'Buenos Aires'),
('Lanús Oeste',                   'Buenos Aires'),
('Avellaneda',                    'Buenos Aires'),
('Sarandí',                       'Buenos Aires'),
('Wilde',                         'Buenos Aires'),
('Villa Domínico',                'Buenos Aires'),
('Almirante Brown',               'Buenos Aires'),
('Adrogué',                       'Buenos Aires'),
('Burzaco',                       'Buenos Aires'),
('Claypole',                      'Buenos Aires'),
('Glew',                          'Buenos Aires'),
('José Mármol',                   'Buenos Aires'),
('Longchamps',                    'Buenos Aires'),
('Rafael Calzada',                'Buenos Aires'),
('Esteban Echeverría',            'Buenos Aires'),
('Monte Grande',                  'Buenos Aires'),
('El Jagüel',                     'Buenos Aires'),
('9 de Abril',                    'Buenos Aires'),
('Canning',                       'Buenos Aires'),
('Ezeiza',                        'Buenos Aires'),
('Florencio Varela',              'Buenos Aires'),
('Quilmes',                       'Buenos Aires'),
('Bernal',                        'Buenos Aires'),
('Ezpeleta',                      'Buenos Aires'),
('Don Bosco',                     'Buenos Aires'),
('San Francisco Solano',          'Buenos Aires'),
('Quilmes Oeste',                 'Buenos Aires'),
('Berazategui',                   'Buenos Aires'),
('Hudson',                        'Buenos Aires'),
('Ranelagh',                      'Buenos Aires'),
('Presidente Perón',              'Buenos Aires'),
('Guernica',                      'Buenos Aires'),
('Cañuelas',                      'Buenos Aires'),
('San Vicente',                   'Buenos Aires'),
('Alejandro Korn',                'Buenos Aires'),

-- Buenos Aires — La Plata y alrededores
('La Plata',                      'Buenos Aires'),
('City Bell',                     'Buenos Aires'),
('Gonnet',                        'Buenos Aires'),
('Los Hornos',                    'Buenos Aires'),
('Villa Elvira',                  'Buenos Aires'),
('Tolosa',                        'Buenos Aires'),
('Berisso',                       'Buenos Aires'),
('Ensenada',                      'Buenos Aires'),
('Brandsen',                      'Buenos Aires'),

-- Buenos Aires — Zona Norte San Miguel
('San Miguel',                    'Buenos Aires'),
('Bella Vista',                   'Buenos Aires'),
('Muñiz',                         'Buenos Aires'),

-- Buenos Aires — Costa Atlántica
('Mar del Plata',                 'Buenos Aires'),
('Batán',                         'Buenos Aires'),
('Sierra de los Padres',          'Buenos Aires'),
('Pinamar',                       'Buenos Aires'),
('Ostende',                       'Buenos Aires'),
('Valeria del Mar',               'Buenos Aires'),
('Carilo',                        'Buenos Aires'),
('Villa Gesell',                  'Buenos Aires'),
('Necochea',                      'Buenos Aires'),
('Quequén',                       'Buenos Aires'),
('Tres Arroyos',                  'Buenos Aires'),
('Claromecó',                     'Buenos Aires'),
('Monte Hermoso',                 'Buenos Aires'),
('Miramar',                       'Buenos Aires'),
('San Clemente del Tuyú',         'Buenos Aires'),
('Mar del Tuyú',                  'Buenos Aires'),
('Santa Teresita',                'Buenos Aires'),
('Las Toninas',                   'Buenos Aires'),
('Costa del Este',                'Buenos Aires'),

-- Buenos Aires — Interior
('Bahía Blanca',                  'Buenos Aires'),
('Ingeniero White',               'Buenos Aires'),
('Punta Alta',                    'Buenos Aires'),
('Tandil',                        'Buenos Aires'),
('Azul',                          'Buenos Aires'),
('Olavarría',                     'Buenos Aires'),
('Sierras Bayas',                 'Buenos Aires'),
('Junín',                         'Buenos Aires'),
('Bragado',                       'Buenos Aires'),
('Chivilcoy',                     'Buenos Aires'),
('Chacabuco',                     'Buenos Aires'),
('Pergamino',                     'Buenos Aires'),
('Arrecifes',                     'Buenos Aires'),
('Ramallo',                       'Buenos Aires'),
('San Pedro',                     'Buenos Aires'),
('Baradero',                      'Buenos Aires'),
('San Nicolás',                   'Buenos Aires'),
('Lincoln',                       'Buenos Aires'),
('9 de Julio',                    'Buenos Aires'),
('Pehuajó',                       'Buenos Aires'),
('General Villegas',              'Buenos Aires'),
('Trenque Lauquen',               'Buenos Aires'),
('Tres Lomas',                    'Buenos Aires'),
('Salliqueló',                    'Buenos Aires'),
('Pellegrini',                    'Buenos Aires'),
('Guaminí',                       'Buenos Aires'),
('Bolívar',                       'Buenos Aires'),
('Coronel Suárez',                'Buenos Aires'),
('Coronel Pringles',              'Buenos Aires'),
('Laprida',                       'Buenos Aires'),
('Benito Juárez',                 'Buenos Aires'),
('Ayacucho',                      'Buenos Aires'),
('Balcarce',                      'Buenos Aires'),
('Dolores',                       'Buenos Aires'),
('Chascomús',                     'Buenos Aires'),
('Roque Pérez',                   'Buenos Aires'),
('Saladillo',                     'Buenos Aires'),
('Las Flores',                    'Buenos Aires'),
('Rauch',                         'Buenos Aires'),
('25 de Mayo',                    'Buenos Aires'),
('General Belgrano',              'Buenos Aires'),
('Lobos',                         'Buenos Aires'),
('Navarro',                       'Buenos Aires'),
('Mercedes',                      'Buenos Aires'),
('San Andrés de Giles',           'Buenos Aires'),
('San Antonio de Areco',          'Buenos Aires'),
('Exaltación de la Cruz',         'Buenos Aires'),
('Capilla del Señor',             'Buenos Aires'),
('Salto',                         'Buenos Aires'),
('Rojas',                         'Buenos Aires'),
('Colón',                         'Buenos Aires'),
('General Arenales',              'Buenos Aires'),
('Leandro N. Alem',               'Buenos Aires'),
('General Pinto',                 'Buenos Aires'),
('General Viamonte',              'Buenos Aires'),
('Los Toldos',                    'Buenos Aires'),
('Alberti',                       'Buenos Aires'),
('Carlos Casares',                'Buenos Aires'),
('Carlos Tejedor',                'Buenos Aires'),
('Rivadavia',                     'Buenos Aires'),
('América',                       'Buenos Aires'),
('Hipólito Yrigoyen',             'Buenos Aires'),
('Henderson',                     'Buenos Aires'),
('Coronel Dorrego',               'Buenos Aires'),
('Puán',                          'Buenos Aires'),
('Pigüé',                         'Buenos Aires'),
('Tornquist',                     'Buenos Aires'),
('Sierra de la Ventana',          'Buenos Aires'),
('Villa Ventana',                 'Buenos Aires'),
('Adolfo Alsina',                 'Buenos Aires'),
('Carhué',                        'Buenos Aires'),
('General La Madrid',             'Buenos Aires'),
('Daireaux',                      'Buenos Aires'),
('Florentino Ameghino',           'Buenos Aires'),
('Capitán Sarmiento',             'Buenos Aires'),
('Carmen de Areco',               'Buenos Aires'),
('Lobería',                       'Buenos Aires'),
('San Cayetano',                  'Buenos Aires'),
('Castelli',                      'Buenos Aires'),
('General Juan Madariaga',        'Buenos Aires'),
('Lezama',                        'Buenos Aires'),
('Maipú',                         'Buenos Aires'),
('General Alvear',                'Buenos Aires'),
('Suipacha',                      'Buenos Aires'),
('Tapalqué',                      'Buenos Aires'),
('Carmen de Patagones',           'Buenos Aires'),
('Médanos',                       'Buenos Aires'),
('General Lavalle',               'Buenos Aires'),
('Pila',                          'Buenos Aires'),
('Punta Indio',                   'Buenos Aires'),
('San Miguel del Monte',          'Buenos Aires'),

-- Catamarca
('San Fernando del Valle de Catamarca', 'Catamarca'),
('Tinogasta',                     'Catamarca'),
('Andalgalá',                     'Catamarca'),
('Santa María',                   'Catamarca'),
('Belén',                         'Catamarca'),
('Fiambalá',                      'Catamarca'),
('Recreo',                        'Catamarca'),
('Londres',                       'Catamarca'),
('La Merced',                     'Catamarca'),
('Santa Rosa',                    'Catamarca'),
('La Paz',                        'Catamarca'),
('Pomán',                         'Catamarca'),
('Icaño',                         'Catamarca'),
('Capayán',                       'Catamarca'),
('El Rodeo',                      'Catamarca'),
('Ancasti',                       'Catamarca'),
('Los Altos',                     'Catamarca'),
('Huillapima',                    'Catamarca'),
('Las Juntas',                    'Catamarca'),
('Aconquija',                     'Catamarca'),

-- Chaco
('Resistencia',                   'Chaco'),
('Presidencia Roque Sáenz Peña',  'Chaco'),
('Barranqueras',                  'Chaco'),
('Fontana',                       'Chaco'),
('Villa Ángela',                  'Chaco'),
('Quitilipi',                     'Chaco'),
('General San Martín',            'Chaco'),
('Las Breñas',                    'Chaco'),
('Charata',                       'Chaco'),
('Juan José Castelli',            'Chaco'),
('Machagai',                      'Chaco'),
('Puerto Tirol',                  'Chaco'),
('Concepción del Bermejo',        'Chaco'),
('Villa Berthet',                 'Chaco'),
('Corzuela',                      'Chaco'),
('General Pinedo',                'Chaco'),
('Gancedo',                       'Chaco'),
('Hermoso Campo',                 'Chaco'),
('Colonia Elisa',                 'Chaco'),
('Napenay',                       'Chaco'),

-- Chubut
('Rawson',                        'Chubut'),
('Comodoro Rivadavia',            'Chubut'),
('Trelew',                        'Chubut'),
('Puerto Madryn',                 'Chubut'),
('Esquel',                        'Chubut'),
('Rada Tilly',                    'Chubut'),
('Gaiman',                        'Chubut'),
('Dolavon',                       'Chubut'),
('Sarmiento',                     'Chubut'),
('Río Mayo',                      'Chubut'),
('Camarones',                     'Chubut'),
('El Maitén',                     'Chubut'),
('Gobernador Costa',              'Chubut'),
('Tecka',                         'Chubut'),
('Paso de Indios',                'Chubut'),
('Cholila',                       'Chubut'),
('Río Pico',                      'Chubut'),
('Alto Río Senguer',              'Chubut'),
('Los Altares',                   'Chubut'),
('Gastre',                        'Chubut'),

-- Córdoba
('Córdoba',                       'Córdoba'),
('Río Cuarto',                    'Córdoba'),
('Villa María',                   'Córdoba'),
('San Francisco',                 'Córdoba'),
('Villa Carlos Paz',              'Córdoba'),
('Cosquín',                       'Córdoba'),
('Alta Gracia',                   'Córdoba'),
('Jesús María',                   'Córdoba'),
('La Falda',                      'Córdoba'),
('Bell Ville',                    'Córdoba'),
('Laboulaye',                     'Córdoba'),
('Río Tercero',                   'Córdoba'),
('Marcos Juárez',                 'Córdoba'),
('Deán Funes',                    'Córdoba'),
('Morteros',                      'Córdoba'),
('Arroyito',                      'Córdoba'),
('Mina Clavero',                  'Córdoba'),
('Villa Allende',                 'Córdoba'),
('Unquillo',                      'Córdoba'),
('Río Ceballos',                  'Córdoba'),

-- Corrientes
('Corrientes',                    'Corrientes'),
('Goya',                          'Corrientes'),
('Paso de los Libres',            'Corrientes'),
('Curuzú Cuatiá',                 'Corrientes'),
('Mercedes',                      'Corrientes'),
('Bella Vista',                   'Corrientes'),
('Esquina',                       'Corrientes'),
('Empedrado',                     'Corrientes'),
('Saladas',                       'Corrientes'),
('Ituzaingó',                     'Corrientes'),
('Santo Tomé',                    'Corrientes'),
('San Luis del Palmar',           'Corrientes'),
('Gobernador Virasoro',           'Corrientes'),
('Monte Caseros',                 'Corrientes'),
('Mburucuyá',                     'Corrientes'),
('La Cruz',                       'Corrientes'),
('Yapeyú',                        'Corrientes'),
('San Miguel',                    'Corrientes'),
('Sauce',                         'Corrientes'),
('Lavalle',                       'Corrientes'),

-- Entre Ríos
('Paraná',                        'Entre Ríos'),
('Concordia',                     'Entre Ríos'),
('Gualeguaychú',                  'Entre Ríos'),
('Concepción del Uruguay',        'Entre Ríos'),
('Colón',                         'Entre Ríos'),
('La Paz',                        'Entre Ríos'),
('Victoria',                      'Entre Ríos'),
('Rosario del Tala',              'Entre Ríos'),
('Nogoyá',                        'Entre Ríos'),
('Villaguay',                     'Entre Ríos'),
('Federación',                    'Entre Ríos'),
('Gualeguay',                     'Entre Ríos'),
('Basavilbaso',                   'Entre Ríos'),
('Diamante',                      'Entre Ríos'),
('San Salvador',                  'Entre Ríos'),
('Chajarí',                       'Entre Ríos'),
('Crespo',                        'Entre Ríos'),
('Federal',                       'Entre Ríos'),
('Seguí',                         'Entre Ríos'),
('Bovril',                        'Entre Ríos'),

-- Formosa
('Formosa',                       'Formosa'),
('Clorinda',                      'Formosa'),
('Las Lomitas',                   'Formosa'),
('Ingeniero Juárez',              'Formosa'),
('Comandante Fontana',            'Formosa'),
('Pirané',                        'Formosa'),
('El Colorado',                   'Formosa'),
('Laguna Yema',                   'Formosa'),
('Ibarreta',                      'Formosa'),
('Palo Santo',                    'Formosa'),
('General Lucio V. Mansilla',     'Formosa'),
('Laguna Blanca',                 'Formosa'),
('Subteniente Perín',             'Formosa'),
('Pozo del Tigre',                'Formosa'),
('Villafañe',                     'Formosa'),
('Gran Guardia',                  'Formosa'),
('Bartolomé de las Casas',        'Formosa'),
('Villa Dos Trece',               'Formosa'),
('Misión Laishí',                 'Formosa'),
('Ing. G. N. Juárez',             'Formosa'),

-- Jujuy
('San Salvador de Jujuy',         'Jujuy'),
('Palpalá',                       'Jujuy'),
('San Pedro de Jujuy',            'Jujuy'),
('Libertador General San Martín', 'Jujuy'),
('Humahuaca',                     'Jujuy'),
('Tilcara',                       'Jujuy'),
('La Quiaca',                     'Jujuy'),
('Perico',                        'Jujuy'),
('El Carmen',                     'Jujuy'),
('Fraile Pintado',                'Jujuy'),
('Abra Pampa',                    'Jujuy'),
('Calilegua',                     'Jujuy'),
('Susques',                       'Jujuy'),
('Purmamarca',                    'Jujuy'),
('Yala',                          'Jujuy'),
('Maimará',                       'Jujuy'),
('Volcán',                        'Jujuy'),
('Santa Catalina',                'Jujuy'),
('Rinconada',                     'Jujuy'),
('Uquía',                         'Jujuy'),

-- La Pampa
('Santa Rosa',                    'La Pampa'),
('General Pico',                  'La Pampa'),
('Realicó',                       'La Pampa'),
('Eduardo Castex',                'La Pampa'),
('General Acha',                  'La Pampa'),
('Macachín',                      'La Pampa'),
('Victorica',                     'La Pampa'),
('Catriló',                       'La Pampa'),
('Intendente Alvear',             'La Pampa'),
('Quemú Quemú',                   'La Pampa'),
('Bernardo Larroudé',             'La Pampa'),
('Trenel',                        'La Pampa'),
('Winifreda',                     'La Pampa'),
('Rancul',                        'La Pampa'),
('Doblas',                        'La Pampa'),
('Lonquimay',                     'La Pampa'),
('Toay',                          'La Pampa'),
('Guatraché',                     'La Pampa'),
('Telén',                         'La Pampa'),
('Ingeniero Luiggi',              'La Pampa'),

-- La Rioja
('La Rioja',                      'La Rioja'),
('Chilecito',                     'La Rioja'),
('Aimogasta',                     'La Rioja'),
('Chamical',                      'La Rioja'),
('Chepes',                        'La Rioja'),
('Famatina',                      'La Rioja'),
('Vinchina',                      'La Rioja'),
('Patquía',                       'La Rioja'),
('Arauco',                        'La Rioja'),
('San Blas de los Sauces',        'La Rioja'),
('Villa Sanagasta',               'La Rioja'),
('Nonogasta',                     'La Rioja'),
('Olta',                          'La Rioja'),
('Malanzán',                      'La Rioja'),
('Tilimuqui',                     'La Rioja'),
('Aminga',                        'La Rioja'),
('Anillaco',                      'La Rioja'),
('Udpinango',                     'La Rioja'),
('Villa Unión',                   'La Rioja'),
('Pagancillo',                    'La Rioja'),

-- Mendoza
('Mendoza',                       'Mendoza'),
('San Rafael',                    'Mendoza'),
('Godoy Cruz',                    'Mendoza'),
('Guaymallén',                    'Mendoza'),
('Las Heras',                     'Mendoza'),
('Maipú',                         'Mendoza'),
('Luján de Cuyo',                 'Mendoza'),
('Rivadavia',                     'Mendoza'),
('General Alvear',                'Mendoza'),
('Junín',                         'Mendoza'),
('San Martín',                    'Mendoza'),
('Tupungato',                     'Mendoza'),
('Tunuyán',                       'Mendoza'),
('Malargüe',                      'Mendoza'),
('San Carlos',                    'Mendoza'),
('Lavalle',                       'Mendoza'),
('Santa Rosa',                    'Mendoza'),
('La Paz',                        'Mendoza'),
('Uspallata',                     'Mendoza'),
('Chacras de Coria',              'Mendoza'),

-- Misiones
('Posadas',                       'Misiones'),
('Oberá',                         'Misiones'),
('Eldorado',                      'Misiones'),
('Puerto Iguazú',                 'Misiones'),
('Apóstoles',                     'Misiones'),
('Montecarlo',                    'Misiones'),
('San Vicente',                   'Misiones'),
('Jardín América',                'Misiones'),
('Leandro N. Alem',               'Misiones'),
('San Ignacio',                   'Misiones'),
('Puerto Rico',                   'Misiones'),
('Aristóbulo del Valle',          'Misiones'),
('Garupá',                        'Misiones'),
('Candelaria',                    'Misiones'),
('San Javier',                    'Misiones'),
('Itaembé Guazú',                 'Misiones'),
('Cerro Azul',                    'Misiones'),
('Campo Grande',                  'Misiones'),
('Dos de Mayo',                   'Misiones'),
('Capiovi',                       'Misiones'),

-- Neuquén
('Neuquén',                       'Neuquén'),
('Plottier',                      'Neuquén'),
('San Martín de los Andes',       'Neuquén'),
('Zapala',                        'Neuquén'),
('Centenario',                    'Neuquén'),
('Cutral-Có',                     'Neuquén'),
('Plaza Huincul',                 'Neuquén'),
('Junín de los Andes',            'Neuquén'),
('Rincón de los Sauces',          'Neuquén'),
('Chos Malal',                    'Neuquén'),
('Las Lajas',                     'Neuquén'),
('Villa La Angostura',            'Neuquén'),
('Loncopué',                      'Neuquén'),
('Caviahue',                      'Neuquén'),
('Piedra del Águila',             'Neuquén'),
('Picún Leufú',                   'Neuquén'),
('Andacollo',                     'Neuquén'),
('El Huecú',                      'Neuquén'),
('Las Coloradas',                 'Neuquén'),
('Mariano Moreno',                'Neuquén'),

-- Río Negro
('Viedma',                        'Río Negro'),
('San Carlos de Bariloche',       'Río Negro'),
('General Roca',                  'Río Negro'),
('Cipolletti',                    'Río Negro'),
('Allen',                         'Río Negro'),
('Villa Regina',                  'Río Negro'),
('San Antonio Oeste',             'Río Negro'),
('El Bolsón',                     'Río Negro'),
('Catriel',                       'Río Negro'),
('Cinco Saltos',                  'Río Negro'),
('Lamarque',                      'Río Negro'),
('Ingeniero Jacobacci',           'Río Negro'),
('Sierra Grande',                 'Río Negro'),
('Choele Choel',                  'Río Negro'),
('Las Grutas',                    'Río Negro'),
('Fray Luis Beltrán',             'Río Negro'),
('Río Colorado',                  'Río Negro'),
('Valcheta',                      'Río Negro'),
('Ñorquinco',                     'Río Negro'),
('Cervantes',                     'Río Negro'),

-- Salta
('Salta',                         'Salta'),
('San Ramón de la Nueva Orán',    'Salta'),
('Tartagal',                      'Salta'),
('Embarcación',                   'Salta'),
('Metán',                         'Salta'),
('Rosario de la Frontera',        'Salta'),
('Cafayate',                      'Salta'),
('General Güemes',                'Salta'),
('Aguaray',                       'Salta'),
('Rosario de Lerma',              'Salta'),
('Cerrillos',                     'Salta'),
('Campo Quijano',                 'Salta'),
('Cachi',                         'Salta'),
('Rivadavia',                     'Salta'),
('Santa Victoria Este',           'Salta'),
('Los Toldos',                    'Salta'),
('Iruya',                         'Salta'),
('Molinos',                       'Salta'),
('La Poma',                       'Salta'),
('Animaná',                       'Salta'),

-- San Juan
('San Juan',                      'San Juan'),
('Rawson',                        'San Juan'),
('Chimbas',                       'San Juan'),
('Rivadavia',                     'San Juan'),
('Caucete',                       'San Juan'),
('Pocito',                        'San Juan'),
('Santa Lucía',                   'San Juan'),
('Valle Fértil',                  'San Juan'),
('Ullum',                         'San Juan'),
('Calingasta',                    'San Juan'),
('Iglesia',                       'San Juan'),
('Angaco',                        'San Juan'),
('Albardón',                      'San Juan'),
('9 de Julio',                    'San Juan'),
('Sarmiento',                     'San Juan'),
('Jáchal',                        'San Juan'),
('Zonda',                         'San Juan'),
('San Martín',                    'San Juan'),
('25 de Mayo',                    'San Juan'),
('Villicum',                      'San Juan'),

-- San Luis
('San Luis',                      'San Luis'),
('Villa Mercedes',                'San Luis'),
('Merlo',                         'San Luis'),
('La Punta',                      'San Luis'),
('Juana Koslay',                  'San Luis'),
('Potrero de los Funes',          'San Luis'),
('San Francisco del Monte de Oro','San Luis'),
('Concarán',                      'San Luis'),
('Justo Daract',                  'San Luis'),
('Quines',                        'San Luis'),
('Luján',                         'San Luis'),
('Naschel',                       'San Luis'),
('La Toma',                       'San Luis'),
('Tilisarao',                     'San Luis'),
('El Trapiche',                   'San Luis'),
('Villa del Carmen',              'San Luis'),
('Nogolí',                        'San Luis'),
('San Martín',                    'San Luis'),
('Beazley',                       'San Luis'),
('Arizona',                       'San Luis'),

-- Santa Cruz
('Río Gallegos',                  'Santa Cruz'),
('Caleta Olivia',                 'Santa Cruz'),
('Pico Truncado',                 'Santa Cruz'),
('Puerto Deseado',                'Santa Cruz'),
('Las Heras',                     'Santa Cruz'),
('El Calafate',                   'Santa Cruz'),
('Gobernador Gregores',           'Santa Cruz'),
('Perito Moreno',                 'Santa Cruz'),
('Los Antiguos',                  'Santa Cruz'),
('Comandante Luis Piedra Buena',  'Santa Cruz'),
('Puerto Santa Cruz',             'Santa Cruz'),
('El Chaltén',                    'Santa Cruz'),
('Río Turbio',                    'Santa Cruz'),
('28 de Noviembre',               'Santa Cruz'),
('Tres Lagos',                    'Santa Cruz'),
('Fitz Roy',                      'Santa Cruz'),
('Puerto San Julián',             'Santa Cruz'),
('Gobernador Mayer',              'Santa Cruz'),
('Hipólito Yrigoyen',             'Santa Cruz'),
('Puerto Madryn',                 'Santa Cruz'),

-- Santa Fe
('Santa Fe',                      'Santa Fe'),
('Rosario',                       'Santa Fe'),
('Rafaela',                       'Santa Fe'),
('Venado Tuerto',                 'Santa Fe'),
('Villa Gobernador Gálvez',       'Santa Fe'),
('Reconquista',                   'Santa Fe'),
('Casilda',                       'Santa Fe'),
('Santo Tomé',                    'Santa Fe'),
('Villa Constitución',            'Santa Fe'),
('Cañada de Gómez',               'Santa Fe'),
('Firmat',                        'Santa Fe'),
('Rufino',                        'Santa Fe'),
('San Lorenzo',                   'Santa Fe'),
('Esperanza',                     'Santa Fe'),
('San Jorge',                     'Santa Fe'),
('Las Rosas',                     'Santa Fe'),
('Avellaneda',                    'Santa Fe'),
('Tostado',                       'Santa Fe'),
('Vera',                          'Santa Fe'),
('Gálvez',                        'Santa Fe'),

-- Santiago del Estero
('Santiago del Estero',           'Santiago del Estero'),
('La Banda',                      'Santiago del Estero'),
('Frías',                         'Santiago del Estero'),
('Añatuya',                       'Santiago del Estero'),
('Termas de Río Hondo',           'Santiago del Estero'),
('Loreto',                        'Santiago del Estero'),
('Quimilí',                       'Santiago del Estero'),
('Fernández',                     'Santiago del Estero'),
('Beltrán',                       'Santiago del Estero'),
('Clodomira',                     'Santiago del Estero'),
('Ojo de Agua',                   'Santiago del Estero'),
('Nueva Esperanza',               'Santiago del Estero'),
('Los Juríes',                    'Santiago del Estero'),
('Monte Quemado',                 'Santiago del Estero'),
('Pinto',                         'Santiago del Estero'),
('Icaño',                         'Santiago del Estero'),
('Villa Atamisqui',               'Santiago del Estero'),
('Colonia Dora',                  'Santiago del Estero'),
('Tintina',                       'Santiago del Estero'),
('Suncho Corral',                 'Santiago del Estero'),

-- Tierra del Fuego
('Ushuaia',                       'Tierra del Fuego'),
('Río Grande',                    'Tierra del Fuego'),
('Tolhuin',                       'Tierra del Fuego'),

-- Tucumán
('San Miguel de Tucumán',         'Tucumán'),
('Concepción',                    'Tucumán'),
('Banda del Río Salí',            'Tucumán'),
('Tafí Viejo',                    'Tucumán'),
('Yerba Buena',                   'Tucumán'),
('Famaillá',                      'Tucumán'),
('Monteros',                      'Tucumán'),
('Aguilares',                     'Tucumán'),
('Alberdi',                       'Tucumán'),
('Bella Vista',                   'Tucumán'),
('Simoca',                        'Tucumán'),
('Graneros',                      'Tucumán'),
('La Cocha',                      'Tucumán'),
('Burruyacu',                     'Tucumán'),
('Trancas',                       'Tucumán'),
('Tafí del Valle',                'Tucumán'),
('Amaicha del Valle',             'Tucumán'),
('Lules',                         'Tucumán'),
('Ranchillos',                    'Tucumán'),
('El Cadillal',                   'Tucumán')

ON CONFLICT (nombre, provincia) DO NOTHING;

-- ── FK en empresas ────────────────────────────────────────────

ALTER TABLE empresas
  ADD COLUMN localidad_id uuid REFERENCES localidades(id) ON DELETE SET NULL;

UPDATE empresas e
SET localidad_id = l.id
FROM localidades l
WHERE lower(trim(e.localidad)) = lower(trim(l.nombre))
  AND lower(trim(e.provincia)) = lower(trim(l.provincia))
  AND e.localidad IS NOT NULL;

ALTER TABLE empresas DROP COLUMN localidad;
ALTER TABLE empresas DROP COLUMN provincia;

CREATE INDEX IF NOT EXISTS idx_emp_localidad
  ON empresas(localidad_id) WHERE localidad_id IS NOT NULL;

-- ── FK en establecimientos ────────────────────────────────────

ALTER TABLE establecimientos
  ADD COLUMN localidad_id uuid REFERENCES localidades(id) ON DELETE SET NULL;

UPDATE establecimientos est
SET localidad_id = l.id
FROM localidades l
WHERE lower(trim(est.localidad)) = lower(trim(l.nombre))
  AND lower(trim(est.provincia)) = lower(trim(l.provincia))
  AND est.localidad IS NOT NULL;

ALTER TABLE establecimientos DROP COLUMN localidad;
ALTER TABLE establecimientos DROP COLUMN provincia;

CREATE INDEX IF NOT EXISTS idx_est_localidad
  ON establecimientos(localidad_id) WHERE localidad_id IS NOT NULL;
